#pragma once

#include <iostream>
#include <charconv>
#include <cstring>
#include <string>
#include <fstream>
#include <dirent.h>
#include <filesystem>
#include <sys/stat.h>
#include <csignal>
#include <algorithm>
#include <stdexcept>
#include <bitset>
#include <ctime>
#include <chrono>
#define VULKAN_HPP_NO_CONSTRUCTORS
#include <vulkan/vulkan.hpp>
#define VMA_IMPLEMENTATION
#include "libs/vma/vk_mem_alloc.h"
#define GLM_ENABLE_EXPERIMENTAL
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtx/hash.hpp>
#include <glm/gtx/rotate_vector.hpp>
#include <glm/gtc/matrix_transform.hpp>
#define STB_IMAGE_IMPLEMENTATION
#include "libs/stb/stb_image.h"
// #include <stb_image.h>
#define TINYOBJLOADER_IMPLEMENTATION
#include "libs/tinyobj/tiny_obj_loader.h"
#include <SDL2/SDL.h>
#include <SDL2/SDL_vulkan.h>
#include <vector>
#include <unordered_map>
#include <optional>
#include <variant>
#include <iomanip>
#include <set>
#include <array>
#include <cstdlib>
#include <cstdint>
#include <limits>
#include <iterator>
